### ISSUE TITLE
Content URLs are not resolveable by the user agent

### ISSUE THREAD

**Issue by JoeCap08055** [ProjectLibertyLabs/social-app-template#50]
# Description
The content URL for content created via `content-publishing-service` is a URL that is resolvable by the `content-publishing-service`. This URL may not be publicly resolvable, as the content-publisher may be running in a different network environment (cloud provider virtual network, containerized network, etc) than a browser or other user agent. URLs provided to the end user-agent must be [publicly] resolvable.

# Proposed solution
Have the social-gateway-template backend rewrite content URLs before providing them to a user agent.

**Comment by wilwade** [comment]
Fixed.
