### ISSUE TITLE
[bug] logout/login as different user does not update app state correctly

### ISSUE THREAD

**Issue by JoeCap08055** [ProjectLibertyLabs/social-app-template#57]
# Description
If logged in to the SAT Frontend, then logout & login as a different user, the app does not refresh correctly for the new logged-in user.

# Scenario/How to Reproduce
1. Log in as user A (here "Foo")
2. Log out
3. Log in as user B (here "Bar")

# Expected Results
When logging in as a different user, the UI should reflect the current logged-in user
expect screen to look similar to this:
![image](https://github.com/AmplicaLabs/social-app-template/assets/83412778/2288e8f6-67d3-4596-8147-a8028d1d4fe2)

# Actual Results
When logging in as a different user, part of the UI shows the correct logged-in user, and part of the UI is for the previous logged-in user.  (See image below: previous logged-in user was "Foo"; current logged-in user is "Bar")

![image](https://github.com/AmplicaLabs/social-app-template/assets/83412778/2596b381-f37c-4cab-9edb-ecfe2e977dad)

**Comment by claireolmstead** [comment]
Was resolved in a previous ticket.
